### PR TITLE
Add test target to JourneySquad project.

### PR DESCRIPTION
**Pull request by kirpichonok**
# What 

Added JourneySquadTest Target to the project. 

# Why 

It's part of the work on issue #16. 

# How 

- Added JourneySquadTest Target with next settings: 
  - Supported Destinations - iPhone only
  - Deployment info - 16.0
  - Target Device Families - iPhone
  - iOS Deployment Target - iOS 16.0
  - Current Project Version - 0
  - Marketing version - 0

### CODE REVIEW

**Review by dersim-davaod — CHANGES_REQUESTED** [review]
Please pay attention to the testing your solution before requesting review.

I see the issue with the Xcode project's tree:
Screenshot 2023-05-12 at 17 25 30

Additionally I don't see the scheme for the test target.
Should we have it?
Screenshot 2023-05-12 at 17 26 55

**Comment by kirpichonok** [comment]
Sorry, I didn't notice the absence of an empty folder for test target.

**Review by dersim-davaod — APPROVED** [review]
LGTM

**Review by levvaa — APPROVED** [review]
LGTM

**Pull request merged**
